name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Create required directories on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_IP }} "mkdir -p /home/ec2-user/app/backend/src/main/resources"

      - name: Copy application-prod.yml to EC2
        run: |
          echo "${{ secrets.YML_PROD }}" > application-prod.yml
          scp -o StrictHostKeyChecking=no -i key.pem application-prod.yml ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app/backend/src/main/resources/application-prod.yml

      - name: Copy docker-compose.yml and project files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r backend frontend README.md ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app

      - name: Deploy using Docker Compose
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_IP }} "
            cd /home/ec2-user/app/backend &&
            sudo docker-compose build --no-cache &&
            sudo docker-compose down &&
            sudo docker-compose up -d
          "
          
      - name: Clean up SSH Key
        run: rm -f key.pem
